### ISSUE TITLE
Element::wrap and how to build

### ISSUE THREAD

**Issue by jots** [lovely-io/lovely.io-stl#25]
Does lovely.io have something like rightjs's "wrap" function, if not, would this do (renamed to "around"):

```
Element.include
  around: (wrapper)->
    element = @_ ; parent = element.parentNode;
    if parent
      wrapper = $(wrapper)._;
      parent.replaceChild(wrapper, element);
      wrapper.appendChild(element);
    return @;
```

Also, how do we build lovely files?  I'd like to create a single file that contains core/dom/dnd/ajax.  I'd like both the minimized
version as well as a non minimized version so I can (hopefully) add things to it via  include without needing to recompile.

**Comment by kaievns** [comment]
No, it was rarely used and always was confusing in the code, so i kicked it out. If you need it you can add it manually in your project. Sorta like you showed, the only difference is that `$` in lovely.io returns a `NodeList` object, which basically an Array. Kind of like jQuery, but every element on the list is an `Element` instance.

## 

Regarding building, there is no building, that's the point, you supposed to be using the centralized CDN hosting which lovely.io provides you. it is backed up by amazon cloud front, and will work faster in production than if you would host it on your own server.

if you're paranoid and wanna do it anyways, then you can download each package from lovely.io server, there are links in the side bar

**Comment by jots** [comment]
Thanks Nikolay,

I changed it to:

``` coffeescript
Element.include
  wrap: (wrapper)->
    element = @_ ; parent = element.parentNode;
    if parent
      wrapper = $(wrapper)[0]._;
      parent.replaceChild(wrapper, element);
      wrapper.appendChild(element);
    return @;
```

I find it a useful function, so I wouldn't complain if you added it to lovely.io :-)

**Comment by kaievns** [comment]
could you try to add it yourself? over here https://github.com/MadRabbit/lovely.io/blob/master/stl/dom/src/element/manipulation.coffee after the #insert method

also would be seriously cool if you could add some working tests for it over here https://github.com/MadRabbit/lovely.io/blob/master/stl/dom/test/unit/element/manipulation_test.coffee

i use `vows` and `zombie` from the NPM repos, after you install them just run

```
vows stl/dom/test/unit/element/manipulation_test.coffee
```

there is also a `cake test` command to run all the tests in the system
