### ISSUE TITLE
DOM NodeList#present method

### ISSUE THREAD

**Issue by kaievns** [lovely-io/lovely.io-stl#64]
would be nice to replace

``` coffee
if $('#some-rule')[0]
```

with something like

``` coffee
if $('#some-rule').present()
```

the code would be more readable this way

**Comment by rwz** [comment]
You mean this?

```
NodeList.prototype.present = function(){ return !!this.length; }
```

**Comment by kaievns** [comment]
`this.length === 0` actually, but yeah, something trivial like this. I also need couple of tests for that too

**Comment by rwz** [comment]
@MadRabbit err, wait, `this.length === 0` means that nodes are NOT present. Since there're zero of them.

You've meant `this.length !== 0`, right?

**Comment by kaievns** [comment]
sure. my point was that `=== 0` (or `!== 0`) is much faster than `!!this.length`
